### ISSUE TITLE
SWT tests for win32 have API errors

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.swt#1298]
**Describe the bug**

With the latest commits, there are API errors in my workspace:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/620f2b92-b8f1-4a65-b942-0ab147a04958)

**To Reproduce**

A freshly Oomphed workspace with just SWT has the problem too:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/790e01d6-0478-4a2e-8765-d043d5a4b63f)

**Expected behavior**

Error freee workspace

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

Windows 10

3. JRE/JDK version
 
**Version since**

Current clone.

**Workaround (or) Additional context**

Delete errors.

**Comment by iloveeclipse** [comment]
The main problem is that **tests** were added to actual SWT production bundle, **not** to the test bundle!
Fix that please and no API comments will be needed.

**Comment by HeikoKlare** [comment]
> The main problem is that **tests** were added to actual SWT production bundle, **not** to the test bundle!
> Fix that please and no API comments will be needed.

For the record: As discussed in #1299 and https://github.com/eclipse-platform/.github/discussions/203, moving these tests to a test bundle is impossible, as they are no integration or system tests (depending on public API only) but actual unit tests, which require access to packages not provided by the bundle or classes that are packaged protected. Thus, they can only be placed in a separate bundle if that bundle is a fragment (or maybe a friend of the to-be-tested packages in the production bundle). Since the to-be-tested code is already placed in a fragment and fragments of fragments are impossible, this test code can only be placed in the production bundle. In my opinion, this can/should be solved by adapting API tooling (as already discussed in #1299, if I see correctly).
