### ISSUE TITLE
Checkbox labels have their last letter cut

### ISSUE THREAD

**Issue by acarstoiu** [eclipse-platform/eclipse.platform.swt#1324]
**Describe the bug**
The last letter of checkbox labels gets cut or sometimes squeezed horizontally, as if the size of the label on the X axis is not computed correctly.

**Screenshots**
This is taken from _Preferences_ window.
![20240705_075819](https://github.com/eclipse-platform/eclipse.platform.swt/assets/9536601/886e408c-74a9-49f4-b0b8-89ea7c78d496)

**Environment:**
Operating System: Gentoo Linux 2.15
KDE Plasma Version: 6.1.1
GTK+: 3.24.41
Kernel Version: 6.9.7-gentoo (64-bit)
Graphics Platform: Wayland
Graphics Processor: AMD Radeon Graphics

**Version since**
Eclipse 4.30 (java.vendor.version=Temurin-21.0.3+9)

**Workaround (or) Additional context**
Using `GDK_BACKEND=x11` does _not_ help. Actually, the attached picture is taken on XWayland.

**Comment by deepika-u** [comment]
I have checked on windows 11 with latest I build and dont see any such problem. So issue looks specific on linux. Thanks @elsazac for adding the label.

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/0a861763-5b6d-4a4a-8815-c1700e0192b7)

**Comment by iloveeclipse** [comment]
I guess this could be GTK theme dependent. Could you please try to use Adwaita?

**Comment by acarstoiu** [comment]
Damn, yes, it's the theme So it's somewhere between GTK+ 3, SWT and KDE's Breeze theme port to GTK+.

**Comment by akurtakov** [comment]
Back in the days when we did the GTK 3 port it was decided that only Adwaita can be properly supported with the time we could  have spent. As GTK3 literally allowed dozens of styling options at every widget it become increasingly hard to get all the sizes proper (especially if a theme uses not so common property). If someone is interested in investigating the issue further it's usually a matter of enhancing some of the compute*Size* methods in respective widget to properly calculate and return the size.

**Comment by acarstoiu** [comment]
The funny thing is that the defect is slightly variable, for the very same checkboxes.

**Comment by iloveeclipse** [comment]
@acarstoiu : you can try to add `-Dorg.eclipse.swt.internal.gtk.noThemingFixes` to the `eclipse.ini` and see if that fixes your theme. The default settings in Eclipse are made for Adwaita, but they may not work nice with other themes.

**Comment by acarstoiu** [comment]
Tested, makes it worse.

**Comment by medmedin2014** [comment]
> I guess this could be GTK theme dependent. Could you please try to use Adwaita?

GNOME is no longer the default desktop for Linux, on Arch based distros [it already lost the battle](https://pkgstats.archlinux.de/fun/Desktop%20Environments/history), and the choice of keeping Adwaita as the default for testing Eclipse is much worse, because GNOME devs are modifying that theme to suite their apps inside their desktop.

Recently, they modified their Adwaita icon theme and is no longer FDO-compatible, [KDE devs reached to them to fix it but without success](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/288), they simply modify things to suite them without any concern for compatibility, that is why Adwaita icon theme was removed as choice in some desktop like [KDE Plasma](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4280) and Cinnamon, because it breaks many apps.

**Comment by akurtakov** [comment]
The default desktop choice on Linux distribution doesn't matter much here as SWT on Linux is implemented on top of GTK and Adwaita is more or less the only GTK theme we can assume will be universally available (or at least easily installable) on every distro.
Alternatives are:
* Someone researches the topic - finds out another universally available theme on Linux, fix quirks with it, test regularly (roughly every 6 months new GTK version comes out) and thus make it the default one
* Someone reimplements SWT on Linux on some other toolkit(e.g. QT)

Until such a thing happens nothing will change on the topic.

**Comment by iloveeclipse** [comment]
> GNOME devs are modifying that theme to suite their apps inside their desktop.

This is really sad and visible through all GTK stack, that the only thing Gnome devs care is Gnome, as if they were only one DE on the world.

> Someone reimplements SWT on Linux on some other toolkit

:-) Yeah. Give me unlimited money & lot of good developers please.

**Comment by laeubi** [comment]
There is already one based on javafx:
https://projects.eclipse.org/projects/technology.efxclipse

Java AWT also seems a good fit (and would be platform independent), but in the end no one is then *that* concerned about it to invest time/money on it (one won't need _unlimited_ resources for that purpose...).

**Comment by vogella** [comment]
> > GNOME devs are modifying that theme to suite their apps inside their desktop.
> 
> This is really sad and visible through all GTK stack, that the only thing Gnome devs care is Gnome, as if they were only one DE on the world.
> 
> > Someone reimplements SWT on Linux on some other toolkit
> 
> :-) Yeah. Give me unlimited money & lot of good developers please.

See https://github.com/swt-initiative31 for prototypes for new SWT implementations.

**Comment by medmedin2014** [comment]
> Someone researches the topic - finds out another universally available theme on Linux, fix quirks with it, test regularly (roughly every 6 months new GTK version comes out) and thus make it the default one


One solution that worked fine for Inkscape and Gimp which are both based on GTK is to create a specific theme for SWT based on any old pure GTK theme then embed it with the library. Instead of begging those arrogant devs to fix their mistake.

With the way how GNOME devs are locking their apps and restrict them from being themed on various Linux desktops, I'm sure in the near future even that Adwaita GTK theme will be butchered by them and will be removed as choice from non GNOME desktops like how it happened with Adwaita icons theme.
