### ISSUE TITLE
New find/replace overlay broken under wayland

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.swt#1447]
Trying to use new find/replace under Wayland is almost entirely impossible, It constantly moves and hides. Just watch the video

https://github.com/user-attachments/assets/9b8085fa-ea45-45ed-934b-e047c1501628

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x ] Linux

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Fedora 40, Gnome on Wayland

4. JRE/JDK version
 Java 23

**Comment by akurtakov** [comment]
@jonahgraham @sratz  That might be interesting for the IDE WG as it will be a problem for users on latest Linux distros

**Comment by HeikoKlare** [comment]
I quickly reproduced the issue on WSL using Wayland. At least one reason seems to be this:
- #790

Setting the shell's location (the one of the find/replace overlay shell) does not work, as also documented here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/790#issuecomment-1699000148
But the find/replace overlay implementation relies on this.

This means, the GTK `Shell` implementation does not behave API-conforming on Wayland. Isn't this an issue also in other use cases? 
And just out of curiosity: Is there a reason for not adding a (temporary) comment to `Shell`'s API that the method will not work on Wayland, given that this issue is known for quite some time now and given that we seem to want / claim SWT to be usable on Wayland?

**Comment by HeikoKlare** [comment]
We show a notification popup to users on first usage of the find/replace overlay to switch back to the existing find/replace dialog. This would give them the chance to easily switch to existing UI (they can of course still switch the UI in the preferences later on).
Unfortunately, this notification popup does also not work properly because of the same issue. Popups also use the `Shell#setLocation()` functionality: https://github.com/eclipse-platform/eclipse.platform.ui/blob/31a902749e53ae095fb98c40459ba8cfc70d6d0d/bundles/org.eclipse.jface.notifications/src/org/eclipse/jface/notifications/AbstractNotificationPopup.java#L422-L423

**Comment by tfonda-fbk** [comment]
For anyone facing this, the workaround mentioned by Heiko is to open Preferences > General > Editors > Text editors and untick "Use find/replace overlay".
@HeikoKlare thanks for fixing this issue. May I ask if I will receive the fix as a software update via the 2024-09 update site, or if I have to wait a few months for the next Eclipse release to get it?

**Comment by merks** [comment]
FYI, you can update from 

https://download.eclipse.org/eclipse/updates/4.34-I-builds/

Also, after M1 is completed next week Thursday morning you can update from

https://download.eclipse.org/releases/milestone/

Of course these things will update many things to current development-in-progress versions which you may not desire.

**Comment by pounard** [comment]
@tfonda-fbk 

> For anyone facing this, the workaround mentioned by Heiko is to open Preferences > General > Editors > Text editors and untick "Use find/replace overlay".

You just saved my life!

**Comment by kurtj-css** [comment]
Using Build id: 20240905-0614 on RHEL9.4. The overlay seems to be implemented as a new window. When the Eclipse IDE has focus, the overlay content can be brought back into place by pressing and Alt-tab key sequence, moving mouse into overlay view and selecting content before it disappears again. Once selected and with focus, the overlay will stay. Depending on how quickly you can get your mouse to the right position in the view, it may take several Alt-tab attempts to keep it. Once focus is lost, the overlay content disappears again. 
While annoying, this does allow the overlay to be used. Without knowing the underlying cause, I don't know if the following is even possible: if a timer (preference option setting?) could be added that allows the overlay content window to stay in place for some number of seconds after focus is lost, and then restored on focus (or continue to be restored on Alt-tab), it would improve the experience.

**Comment by HeikoKlare** [comment]
The issue has been fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/2254 and should not be present in the 2024-12 release anymore.
