### ISSUE TITLE
Add information about SWT experimental work to README

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.swt#1580]
https://github.com/swt-initiative31 contains experimental work to re-implement SWT. We should add a link to it to the readme so that other can discover this.

Also it would be nice to have some "Getting started with the prototyp" documentation in https://github.com/swt-initiative31 and link it from here.

**Comment by HeikoKlare** [comment]
We now have some documentation for getting started with the prototypes in their readme documents. Active work happens on the following prototypes:
- Custom-drawn widgets with Ski(j)a: https://github.com/swt-initiative31/prototype-skija
- Cross-platform GTK: https://github.com/swt-initiative31/prototype-gtk

There is also a prototype based on Swing that can be tested, but we currently do not plan to proceed with that technology: https://github.com/swt-initiative31/prototype-swing

If you experience any difficulties with following the descriptions in the readme documents, please let us/me know, so that we can improve them (or just make a PR with the improvements on those repositories).

@vogella would you propose to add those links to the readme of _this_ repository or somewhere else?
