### ISSUE TITLE
GitHub unit tests are testing irrelevant swt.jar

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#251]
** Summary **
When GitHub is running unit tests for a pull request, it tests latest published SWT instead of SWT in the pull request!

** Analysis **
In #245 I ran into a problem where GitHub side unit tests fail with error `java.lang.SecurityException: class "org.eclipse.swt.graphics.ImageDataTestHelper"'s signer information does not match signer information of other classes in the same package`.

Eventually I added this code in my unit test
```
Class swtClass = SWT.class;
Class tstClass = Test_org_eclipse_swt_SWT.class;
URL swtURL = swtClass.getProtectionDomain().getCodeSource().getLocation();
URL tstURL = tstClass.getProtectionDomain().getCodeSource().getLocation();
```

and ran maven locally (where the problem is also reproducible). The output was
```
SWT: (file:/C:/Users/User/.m2/repository/p2/osgi/bundle/org.eclipse.swt.win32.win32.x86_64/3.121.0.v20220701-1002/org.eclipse.swt.win32.win32.x86_64-3.121.0.v20220701-1002.jar [
  Version: V3
  Subject: EMAILADDRESS=webmaster@eclipse.org, CN="Eclipse.org Foundation, Inc.", OU=IT, O="Eclipse.org Foundation, Inc.", L=Ottawa, ST=Ontario, C=CA
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11
  <...>])
TST: (file:/C:/Path/eclipse.platform.swt/tests/org.eclipse.swt.tests/target/classes/ <no signer certificates>)
```

That is, when running unit tests, maven uses a published SWT instead of the one built from the repo!

**Comment by iloveeclipse** [comment]
@laeubi : FYI. 
If it can't be fixed, we should remove the githib test matrix from PR's, otherwise it suggests something that is completely irrelevant.

**Comment by SyntevoAlex** [comment]
I submitted #252 with a unit test to demonstrate the problem. In its GitHub tests, I can see the problem being reported in the new test:

```
java.lang.AssertionError: Tested SWT path is on maven cache: (

SWT='/Users/runner/work/eclipse.platform.swt/eclipse.platform.swt/eclipse.platform.swt/tests/org.eclipse.swt.tests/Users/runner/.m2/repository/p2/osgi/bundle/org.eclipse.swt.cocoa.macosx.x86_64/3.121.0.v20220701-1002/org.eclipse.swt.cocoa.macosx.x86_64-3.121.0.v20220701-1002.jar'

Test='/Users/runner/work/eclipse.platform.swt/eclipse.platform.swt/eclipse.platform.swt/tests/org.eclipse.swt.tests/Users/runner/work/eclipse.platform.swt/eclipse.platform.swt/eclipse.platform.swt/tests/org.eclipse.swt.tests/target/classes'
```

This once again confirms that SWT is used from maven cache (and according to my previous testing, it's also signed with Eclipse's cert, which clearly indicates that this is not the SWT built in the PR)

**Comment by SyntevoAlex** [comment]
The problem is not (only) about GitHub, but about maven build configuration (which is also used by GitHub). The problem is reproducible when building with maven locally.

**Comment by laeubi** [comment]
@iloveeclipse the problem also show up in the jenkins:
https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-252/4/testReport/junit/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_SWT/test_isLocal/

**Comment by laeubi** [comment]
@SyntevoAlex I think one needs to build the SWT fragments explicitly first, lets finish the test you supplied (it needs a minor adjustment) then we can merge the test and start fixing the issue with the build.

**Comment by laeubi** [comment]
@SyntevoAlex It seems the test needs to consider one more case (see https://github.com/eclipse-platform/eclipse.platform.swt/pull/293#issuecomment-1207955374) when base-line replace takes place (because nothing has changed) the the file is located e.g at the following path:

D:/a/eclipse.platform.swt/eclipse.platform.swt/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/target/org.eclipse.swt.win32.win32.x86_64-3.121.0-SNAPSHOT.jar

do you like to adjust the test-case to ignore the signing in cases where it is located in the target folder?

**Comment by SyntevoAlex** [comment]
If you know how to adjust, please go forward.

**Comment by SyntevoAlex** [comment]
Hmm I still don't understand.
Consider my latest PR: #318

In it, my test fails with
```
java.lang.AssertionError: Tested SWT is signed by Eclipse: (SWT='D:/a/eclipse.platform.swt/eclipse.platform.swt/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/target/org.eclipse.swt.win32.win32.x86_64-3.121.0-SNAPSHOT.jar' signer='1.2.840.113549.1.9.1=#16157765626d61737465724065636c697073652e6f7267,CN=Eclipse.org Foundation\, Inc.,OU=IT,O=Eclipse.org Foundation\, Inc.,L=Ottawa,ST=Ontario,C=CA')
```

How is that even possible, now that my PR certainly changes SWT (on win32 platform, where test also fails) ?
I mean, how can it be signed? To me, this means that once again GitHub tests something but NOT my PR.

**Comment by laeubi** [comment]
> How is that even possible, now that my PR certainly changes SWT (on win32 platform, where test also fails) ?

As I already explained the artifact is replaced with the baseline version (**and that version is signed!**), please see the build logs:

```
 [WARNING] MavenProject: org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:3.121.0-SNAPSHOT @ D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt.binaries\bundles\org.eclipse.swt.win32.win32.x86_64\pom.xml: baseline and build artifacts have same version but different contents
[INFO] MavenProject: org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:3.121.0-SNAPSHOT @ D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt.binaries\bundles\org.eclipse.swt.win32.win32.x86_64\pom.xml
     The main artifact has been replaced with the baseline version.
     The following attached artifacts have been replaced with the baseline version: [sources]
```

this has nothing to do with the github actions, I can see in the logs that the bundle is actually compiled and installed as expected.

**Comment by SyntevoAlex** [comment]
Previously you said
> Yes that means that the code is compiled, compared with the baseline and then it was detected that they are equal and thus replaced with the signed(!) baseline artifacts.

But I clearly changed SWT in this PR, so it cannot be seen as equal. Whether it's compiled or not (and I agree that it's compiled), my test indicates that JUnit tests are run against signed jar, which can't be a result of current buid (because GitHub shall not have signing keys), therefore I understand that tests are run against irrelevant SWT, therefore I understand that original issue is still there.

**Comment by SyntevoAlex** [comment]
If by "compared to baseline" you mean the version numbers, then this doesn't help either, because 99% of PRs do not change version numbers.

**Comment by laeubi** [comment]
> But I clearly changed SWT in this PR, so it cannot be seen as equal.

That's why you get a warning

> If by "compared to baseline" you mean the version numbers, then this doesn't help either, because 99% of PRs do not change version numbers.

Then this is wrong, if you change the code, the version needs to be incremented at least once in a release and then it won't be replaced by the baseline version.

> therefore I understand that original issue is still there.

Your understanding is wrong. Baselinereplace has nothing to do with Girhubactions but will happen on any CI system.

**Comment by SyntevoAlex** [comment]
I still don't understand. You could call me a fool, but on the other hand, according to `$ git shortlog -s -n --no-merges --since="01 jan 2021"`,  I'm top committer #3 in SWT in the last couple years, so it's not like I have no experience at all.

* Is my PR #318 well formed on not?
* If not, are all other PRs also ill-formed?
* If it's well-formed, does it make any sense that unit tests are run against irrelevant SWT version (not containing any changes from the PR) and then irrelevant unit tests results are reported in the PR ?
* Or are you stating that despite my test saying that tested SWT is signed, it somehow contains changes from the tested PR?

**Comment by laeubi** [comment]
@SyntevoAlex as mentioned before, any contributions are welcome, so if you think you can fix/improve anything here, feel free to propose a patch, I can only tell that

1. The SWT fragment code is compiled and the build log proves this
2. The tested SWT.jar is signed because **it is replaced with the baseline version** because the version of the baseline and the version of the build are equal to each other so **any change compiled before will be irrelevant** because it is instantly overwritten with the baseline version! So you might wan't to 

To my knowledge this can only be fixed by bumping the version **of the SWT fragment** that is **not** part of this repository, but part of the  https://github.com/eclipse-platform/eclipse.platform.swt.binaries so any changes in a PR in this PR will never change that version there but @mickaelistria know more about the baselinereplace and might shade some more light on this, and maybe some obscure things are happening inside the ant script but until now *no one of the SWT committers either:

1. Know enough about that
2. Don't bother to share any insights

so from the point of view of GH actions there is nothing we can do right now..

**Comment by SyntevoAlex** [comment]
It makes sense to re-open the issue if you agree that there's currently a problem with unit testing for for a typical PR (and a typical PR doesn't change any version numbers). All my discussion was because you declared issue o be solved, and I couldn't understand it given the various facts I listed.

**Comment by laeubi** [comment]
> All my discussion was because you declared issue o be solved, and I couldn't understand it given the various facts I listed.

Please open a new ticket this ticket describes a state where GH actions do not build the fragments at all, the current problem/disturbance is a different story and is not specific to GH actions but to how SWT is build in general!

**Comment by SyntevoAlex** [comment]
Maybe you're confusing issues? I'm re-reading top post in this issue and it's exactly about testing wrong SWT.

**Comment by vogella** [comment]
I agree with @SyntevoAlex. Let's use this issue for the issue that latest SWT binary is not used for pr validation.

**Comment by laeubi** [comment]
> I agree with @SyntevoAlex. Let's use this issue for the issue that latest SWT binary is not used for pr validation.

Sorry for being rough but is **anyone** actually **reading** what is written here?

The latest SWT binaries **are used** if you bump the version because otherwise **they are replaced** this is nothing special and is the case for every other platform project as well!

Just for demonstration purpose I bumped the fragments versions here:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/323

and ... surprise surprise ... the test **passes**. So sometimes it would be useful even for "SWT top committers since 2021" to consider that what "top committers of the tool used here since whatever" are also have some experience and it might be worth to not think they are totally dumb.

So from my side, the only issues left,  but none of them are related to this ticket are:

1. Versions where not bumped (I don't know if this will still work because some aggregator/ant magic in the final build but no one yet cared so investigate or explain this)
2. The test-case added is flawed, as it incorrectly assumes that the SWT jar is never signed (what is wrong) and should be adjusted as already explained here https://github.com/eclipse-platform/eclipse.platform.swt/issues/251#issuecomment-1207957956
3. It might be a very inconvenient workflow as one needs to change two repositories, this was already discussed somewhere by e.g. merging repos, using submodules, LFS but no one has cared enough to proceed there yet
4. The warning is somewhat hidden in the log but see PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/319 to improve this
5. I would have expected that there is even some error when version bumps are missing, but that more the area of @mickaelistria and @akurtakov 
6. There might be some magic / alternative setup to archive something similar, the GH action setup is simply inspired by the aggregator build.

**Comment by akurtakov** [comment]
Too much content written so I'll try to summarize what happens in the Jenkins build to make the tests use the just built natives:
* build and install (mvn install) eclipse.platform.swt.binaries first https://github.com/eclipse-platform/eclipse.platform.swt/blob/a3ebd662f200a4eb556e0d7cb867e275a32d3738/Jenkinsfile#L102
** this has to be first as these fragments contain the native code
** -Dnative=gtk.linux.x86_64 is passed to this build to force rebuild of the *.so files. Note: I don't think that releng ever tested this works for Win/Mac, at least I have never done that.
** -DforceContextQualifier=zzz is passed to the build of natives, this qualifier is lexicographically always after what we build so it overrides what's in the I-build repo. There are warnings in the build about that "[WARNING] The following locally built units have been used to resolve project dependencies:
[WARNING]   org.eclipse.swt.gtk.linux.ppc64le/3.121.0.zzz
[WARNING]   org.eclipse.swt.gtk.linux.x86_64/3.121.0.zzz"
** Fragments generated that way contain the latest java bytecode and native libraries
* Build eclipse.platform.swt repository 
** The build of org.eclipse.swt bundle is meaningless here as at the end it's empty shell
** Build and run of tests is done using the fragments built and installed during the eclipse.platform.swt.binaries repo and that way it ensures that latest java and native changes are used.

Hope that helps!

**Comment by laeubi** [comment]
@akurtakov currently the binary code is not compiled, so it simply uses the precompiled ones like the aggregator-build does.

Beside that, the "native build" simply do not enable baseline replace, but uses a different technique here to fetch locally build artifacts, using an aggregator like for the GH actions would work the same.

So if versions are bumped and baselinereplace thus do not com into play, everything works as expected!

If anyone thinks that:

- Baseline replace should not be applied to fragments, then it must be disabled (not related to this problem)
- Baseline replace is doing something wrong, then Tycho must be fixed (not related to this problem)
- Aggregator build is doing it differently or doing it wrong then we might adjust either of those (not related to this problem)
- Binaries should actually be build, I would be happy if someone can explain how and help adjusting the github actions (not related to this problem)

**Comment by akurtakov** [comment]
Note that in I-builds one of the very first steps is to prebuild natives if needed - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/29340229f4679c8512c532b20744de0d02796181/JenkinsJobs/Builds/I-build.groovy#L183 and thus we know that natives are correct when aggregator build starts, this can't be easily made part of the maven build as the native build literally ssh into 5 different remote machines to get the natives built.
AFAICT baseline replace works as expected in aggregator build, it's the complicated SWT fragment build which forces the Jenkins verification build to use the zzz qualifier to ensure these will always override, -DforceContextQualifier=zzz should make version bump not needed. 
It literally costed me months to make the current (complicated) setup to work back in the days. It certainly can be improved but is not the most pressing problem for now. E.g. even on Jenkins there is one constantly [failing test](https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/598/), the other long failing one was a nasty [pango behavior change](https://github.com/eclipse-platform/eclipse.platform.swt/commit/ae7dd516893178e5294606c2ff2260adaed3d77d) fixed last week. So I would rather concentrate on getting Jenkins working correctly before jumping into GH.

**Comment by laeubi** [comment]
> it's the complicated SWT fragment build which forces the Jenkins verification build to use the zzz qualifier to ensure these will always override, -DforceContextQualifier=zzz should make version bump not needed.

From your liked Jenkins file:

> -Dcompare-version-with-baselines.skip=true

so basically `compare-version-with-baselines` is **disabled** there, so a missing version bump won't be detected!

> So I would rather concentrate on getting Jenkins working correctly before jumping into GH.

GH is working correctly as proven by the PR ... but you need to bump the version, and I would expect this for any Javachange and any native code change.

**Comment by SyntevoAlex** [comment]
> Sorry for being rough but is anyone actually reading what is written here?

> The latest SWT binaries are used if you bump the version because otherwise they are replaced this is nothing special and is the case for every other platform project as well!

> GH is working correctly as proven by the PR ... but you need to bump the version, and I would expect this for any Javachange and any native code change.

Let's see how many commits do change the version number. I took last 3 years.
```
$ git shortlog -s -n --no-merges --since="3 years ago" -- bundles/org.eclipse.swt/pom.xml
   573  Eclipse Releng Bot
   115  genie.releng
    13  Alexander Kurtakov
     8  Sravan Kumar Lakkimsetti
     4  Niraj Modi
     2  Andrey Loskutov
     2  Christoph Läubrich
     2  Joerg Kubitz
     2  Mat Booth
     2  Mickael Istria
     2  Nikita Nemkin
     1  Alexandr Miloslavskiy
     1  Eric Williams
     1  Guillermo Zunino
     1  Jörg Kubitz
     1  Kit Lo
     1  Paul Pazderski
     1  Samantha Dawley
```

Removing the top two lines added by bots, actual humans created 44 commits that alter the file. I bet, almost all of these commits are related to some maintenance, which is not connected to any changes that could be tested by JUnit.

Fine, now let's count how many commits total are there:
```
$ git shortlog -s -n --no-merges --since="3 years ago"
   728  Eclipse Releng Bot
   185  Paul D'Pong
   159  Alexander Kurtakov
   138  genie.releng
   127  Alexandr Miloslavskiy
   104  Niraj Modi
    73  Lakshmi Shanmugam
    65  Nikita Nemkin
    62  Sravan Kumar Lakkimsetti
    45  Paul Pazderski
    44  Andrey Loskutov
    42  Joel Majano
    37  Lars Vogel
    33  Carsten Hammer
    32  Eric Williams
    25  Jonah Graham
    21  Mickael Istria
    21  Simeon Andreev
    17  Joerg Kubitz
    16  Christoph Läubrich
    16  Александър Куртаков
     9  Jonathan Meier
     8  Karsten Thoms
     8  Thomas Singer
     7  jmajano
     6  Ed Merks
     6  Lakshmi P Shanmugam
     6  Rolf Theunissen
     5  Jörg Kubitz
     5  Vikas Chandra
     4  Conrad Groth
     4  Thomas Wolf
     3  Dirk Steinkamp
     3  Jason Wang
     3  Mat Booth
     3  Phillipus
     3  Sebastian Ratz
     3  Till Brychcy
     2  Eike Stepper
     2  Guillermo Zunino
     2  Jeeeyul Lee
     2  Will Rogers
     1  Adrien Thierry
     1  Alex Blewitt
     1  Alexander Fedorov
     1  Alexandra Buzila
     1  Alexandre Honorat
     1  Amit Mendapara
     1  Andreas Holtz
     1  Andrew Obuchowicz
     1  Denis Ungemach
     1  Gayan Perera
     1  Gunnar Wagenknecht
     1  Hannes Wellmann
     1  Jens Lidestrom
     1  Julian Jung
     1  Kit Lo
     1  Marcus Hoepfner
     1  Mauro Garcia
     1  Michael Keppler
     1  Mikaël Barbero
     1  Paul D'\''Pong
     1  Samantha Dawley
     1  Stefan Kowski
     1  Thomas Rohwer
     1  fyaling
     1  joel-majano
     1  mgolubev
     1  rolfth
```

That makes 1245 commits.

Conclusions: at most, 44/1245~=3.5% of commits are "good" from your perspective where "GH is working correctly". The remaining 96.5% of commits are, well, where your requirement is not satisfied, it seems. Furthermore, I estimate that even the "at most 3.5%" is wrong, because those commits are not changing actual SWT code, and in practice, entire 100% commits do not satisfy your requirement.

Note that to my memory, no real SWT changes are committed to `eclipse.platform.swt.binaries` repo, ever.

**Comment by SyntevoAlex** [comment]
It doesn't make much sense to me when you continue to assert that issue is resolved, everything works fine, when some 96.5% to 100% of actual commits do not satisfy your requirements (where you require that version must be changed for every code change).

**Comment by sravanlakkimsetti** [comment]
Version number consists of <major>.<minor>.<service>-<qualifier>. In case of SWT none of these gets changed during validation job. 

In case of other plugins the qualifier gets calculated by tycho during the build that makes the version number updated and different version than I-build. Since SWT doesn't use qualifier calculated by tycho, we end up with the same version as I-build. Since qualifier always starts with character 'v' using 'zzz' should help

**Comment by akurtakov** [comment]
I consider this one done as noone pointed to remaining issue.
