### ISSUE TITLE
Regression drawing image arising from fix to #185 and other regressions in Image class

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#301]
Windows only.

There have been a few  changes to the way transparency is handled in the `Image` class on Windows from @jonathan-meier recently. However, we were left with a bug that caused problems that was apparently fixed here with https://github.com/eclipse-platform/eclipse.platform.swt/issues/185

Unfortunately this fix has caused yet another bug which now makes our RCP application broken when targetted with the latest SWT version.

The regression is caused by the fix in 8def011fdd013543a5ea5513dacef5914c3c8662 - however the underlying cause is somewhere deeper than that arising from previous changes to `Image` class on Windows

I have put together a snippet that shows the problem (see later post)

If you run the snippet with a version of SWT prior to 8def011fdd013543a5ea5513dacef5914c3c8662 a red box should be drawn:

![correct](https://user-images.githubusercontent.com/600504/183751932-92deb908-7c44-4f29-9d9c-f0927d0b68fe.png)

But running the snippet with a version of SWT after 8def011fdd013543a5ea5513dacef5914c3c8662 gives a wrong colored image:

![incorrect](https://user-images.githubusercontent.com/600504/183752062-7c9e0b30-c625-4085-945c-c0f34846e35d.png)

**Comment by Phillipus** [comment]
Here is the test snippet:

```java
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class ColorBug {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setText("Image Color Bug");
        shell.setSize(300, 200);
        shell.setLayout(new GridLayout());
        
        Image image = new Image(display, getImageData());
        
        shell.addPaintListener(e -> {
            e.gc.drawImage(image, 0, 0);
        });
        
        shell.open();
        
        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
        
        display.dispose();
        image.dispose();
    }
    
    static ImageData getImageData() {
        Image tmp = new Image(Display.getDefault(), 100, 100);
        
        GC gc = new GC(tmp);
        gc.setBackground(new Color(255, 0, 0));
        gc.fillRectangle(0, 0, 100, 100);
        gc.dispose();
        
        ImageData id = tmp.getImageData(100);
        tmp.dispose();
        
        return id;
    }
}
```

**Comment by Phillipus** [comment]
The problem with these changes from @jonathan-meier is that we are still uncovering regressions that affect how Images are handled on Windows. And for a production RCP app such as ours these regressions have a negative impact and mean that we cannot build on the latest version of Eclipse in order to resolve other regressions.

Would it be over-stepping the mark to ask for the following changes to be reverted?

def5c63081058881bcce98004349276f577bd32f
22797d3f9f09ca67bfd29c864f2aaf8eb452c75c
8def011fdd013543a5ea5513dacef5914c3c8662

**Comment by SyntevoAlex** [comment]
I would rather give @jonathan-meier some time to fix it. I understand that the entire work is not trivial, and connected to older bugs that were lurking in SWT without being noticed. It's not too good to just revert things whenever something happens. This way, a large work has chances to be abandoned completely.

**Comment by Phillipus** [comment]
> I would rather give @jonathan-meier some time to fix it. I understand that the entire work is not trivial, and connected to older bugs that were lurking in SWT without being noticed. It's not too good to just revert things whenever something happens. This way, a large work has chances to be abandoned completely.

Sure, but I am afraid that @jonathan-meier is no longer involved with supporting these changes.

Here is my problem:

1. We have a free RCP app, Archi (which is generally downloaded about 7000 times very month)
2. We currently build on Eclipse 4.23 but this has a regression that involves RTL text not rendering correctly so we would like to upgrade...
3. So we try to use Eclipse 4.24....but this has an issue with drawing *,ico images and no menus on upcoming macOS Ventura,,,
4. So we try to use Eclipse 4.25...but this has this regression with drawing images....
5. So what now? Wait for Eclipse 4,26...4.27....4.28....? 

Sorry for my complaint but this is getting so stressful that I am seriously considering abandoning Archi.

**Comment by SyntevoAlex** [comment]
One possible approach would be to either
* Cherry-pick desired fixes to older version
* Revert what causes problems in newer version
and build SWT yourself. That's how we do it in our product.

**Comment by Phillipus** [comment]
> and build SWT yourself. That's how we do it in our product.

I know. But I don't have the ability to do that.

But now I am getting off-topic and don't want to derail the original issue.

**Comment by Phillipus** [comment]
Here is another test snippet. With the older, working, version of SWT it should draw a black box but with the new version it is transparent.

Interestingly, if the Color is changed to ` Color color = new Color(1, 0, 0);` it is not transparent.

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class ColorBug2 {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setText("Image Color Bug 2");
        shell.setSize(300, 200);
        shell.setLayout(new GridLayout());
        
        Button button = new Button(shell, SWT.FLAT);
        Image image = new Image(display, getImageData());
        button.setImage(image);
        
        shell.open();
        
        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
        
        display.dispose();
        image.dispose();
    }
    
    private static ImageData getImageData() {
        Image tmp = new Image(Display.getDefault(), 100, 70);
        
        // Change this and it's not transparent:
        // Color color = new Color(1, 0, 0);
        Color color = new Color(0, 0, 0);
        
        GC gc = new GC(tmp);
        gc.setBackground(color);
        gc.fillRectangle(0, 0, 100, 70);
        gc.dispose();
        
        ImageData id = tmp.getImageData(100);
        tmp.dispose();
        
        return id;
    }
}
```

**Comment by jonathan-meier** [comment]
This is indeed a regression of PR #244 (Issue #185). I provided a fix in PR #301. Please test my patch and also make sure that issue #185 is not reintroduced by it.

Instead of allowing alpha channel data in `ImageData.data` only for icons when initializing an `Image`, PR #244 also allowed this for bitmaps, which does not work. Alpha channel data in `ImageData.data` always has to be ignored and only read from `ImageData.alphaData` for bitmaps.

Unfortunately, `Image.getImageData` as used in the reproducer snippets above (thanks for providing them @Phillipus!) returns alpha channel data in `ImageData.data` that is problematic for the initialization of the `Image` later on (it is set to fully transparent instead of fully opaque). I improved this situation as well in my PR to make the result of `Image.getImageData` more compatible even though alpha channel data in `ImageData.data` should always be ignored for bitmaps.

As a workaround for the current SWT version one can fix the `ImageData` by overwriting the alpha channel data manually before constructing an `Image` from it:
```
static void makeOpaque(ImageData imageData) {
    if (imageData.depth != 32) {
    	return;
    }
    byte[] data = imageData.data;
    for (int dp = 3; dp < data.length; dp += 4) {
    	data[dp] = (byte) 0xFF;
    }
}
```

**Comment by Phillipus** [comment]
@jonathan-meier Thank-you for reacting so swiftly to address this issue. I appreciate it, as I had found so many cases of broken images, buttons, palette, etc in our app that I was worried about what to do.

I just tested your patch and it seems to have fixed the issue.

I tested the two snippets above, and the one in #185, and have tested it in our app, [Archi ](https://www.archimatetool.com) and so far everything seems to be as it should.

Thanks once again!

Is it possible for someone to merge https://github.com/eclipse-platform/eclipse.platform.swt/pull/303 ?

**Comment by turesheim** [comment]
I don't know if it's related, but I found a possible SWT bug on macOS when dealing with transparency, using `org.eclipse.swt 3.119.0.v20220223-1102`. Basically I'm creating a transparent image (in order to get a transparent background) and using this as a base to draw the actual image I want. This works perfectly, except when displaying on my external monitor using its native resolution – this would cause everything to be transparent. Changing the background transparency to e.g. 50% shows that the image is there. However using the macOS control panel to switch resolution in this monitor for bigger text – results in the image being drawn as is should. Interestingly, switching back to the native resolution using a cached image will also display it correctly. I am using the `Display` instance from the parent so this should be in order.

The issue appears to be related to handling of HiDPI displays. Please advise whether I should create a new issue report.

**Comment by Phillipus** [comment]
> Please advise whether I should create a new issue report.

Hi, my 2 cents is I think you should do that. The changes that were made to the `Image` class in this issue and related issues were specifically for Windows. macOS does things differently.
