### ISSUE TITLE
Inconsistent behavior of Composite.setFocus across operating systems

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.swt#616]
**Describe the bug**
The behavior of `setFocus` of a `Composite` is different between Linux and the other operating systems. While the [Linux implementation](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/Composite.java#L1672) only tries to set focus on children when they are visible, the [implementation for Windows](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/widgets/Composite.java#L1078-L1080) and [the one for MacOS](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/cocoa/org/eclipse/swt/widgets/Composite.java#L1127) call `setFocus` on their children even if they are invisible. This can lead to unexpected behavior such as views processing `setFocus` (with potentially complex functionality) while they are not visible. An example can be seen in the  `TextMergeViewer`, which is recalculated every time one of the compared documents is saved, even if it is not visible. This is due to all views being temporarily disabled while saving, which in turn triggers a call of `setFocus`: eclipse-platform/eclipse.platform#121

Of course, a view should not process complex logic in `setFocus` when it is not visible. However, the framework could at least avoid that views that are not even visible perform actions for which the user does not understand where they belong, as they do not see the view.

**To Reproduce**
Taken from eclipse-platform/eclipse.platform#121:
1.) Do a change to a larger text and displays its delta via the compare editor
2.) Ensure the compare editor is not visible
3.) Perform changes in other files and save -> Frequently you see "Calculating deltas" in the job monitor
4.) Change the file itself in a regular editor -> -> Frequently you see "Calculating deltas" in the job monitor

**Expected behavior**
I would expect that propagating `setFocus` to children is not necessary when they are invisible. Thus I propose to add a check for whether children are visible before trying to set focus to them for Windows and MacOS, as already implemented for Linux. At least, I would expect the behavior to be consistent across systems.

**Screenshots**
![image](https://user-images.githubusercontent.com/755472/230432010-48dda786-cd4a-434b-aa19-1200f94a8b99.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11 10.0.22000

3. JRE/JDK version
Adoptium 17.0.6.10

**Version since**
Must have been the case for all versions in the last years.

**Workaround (or) Additional context**
Have all views check `isVisible` before processing complex logic in `setFocus` on their own.

**Comment by ChristianR2** [comment]
A problem I saw in the past might worsen by this, so I think I mention it here, so that someone with more insight can check if the intended change affects this:

In the past I experienced problems in an RCP application with key bindings that worked properly on Windows but not on Linux. The key bindings (I intended to be global) depended on the currently focused UI element. In many situations I had an active view but activating this on Linux did not accept the focus (probably because there was no focusable element in it). On windows the focus was taken anyway, Linux had a "null" focus. After clicking somewhere in the view, the key binding worked. I believe even then I did not need to find a focusable element and the click was enough. I experienced this on RCP 4.9 but still see it on RCP 4.27.

If rejecting the focus now on all OS, it could be that key bindings break totally for me.

**Comment by iloveeclipse** [comment]
@ChristianR2 : not sure if you saw [this issue](https://github.com/eclipse-platform/eclipse.platform.ui/issues/686) which I've reported while using Linux (I haven't checked if that is reproducible on Windows) and if that is what you've observed in your RCP.

Note: my issue, and the issue that you've mentioned is most likely IDE/RCP issue (to make sure keybindings work independently of what is active or not) and not issue of SWT that just provides widgets API for Platform UI to build on.

**Comment by ChristianR2** [comment]
@iloveeclipse Thanks. It seems indeed the issue you reported there. I added to the platform UI bug to indicate it happens on Linux not Windows.

**Comment by pbodnar** [comment]
@all, thanks for looking at this issue. It looks very promising performance-wise! It would be great to have this in the next Eclipse release version `2023-??`.

So as #617 which links to this issue got merged to the master, this issue and the parent issue eclipse-platform/eclipse.platform#121 can be closed now?

Also I wonder if someone tested the impact of this fix on eclipse-platform/eclipse.platform.ui/issues/686. What were the results?

**Comment by SyntevoAlex** [comment]
Unfortunately this patch's test `test_setFocus_withVisibleAndInvisibleChild` now very often fails.
This adds significant noise in all other PRs, because it looks as if other PRs introduced test failures.

For example, see PR that didn't even touch any code and has this test failing:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/714/checks?check_run_id=14613072507

Same problem can be seen in other PRs:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/630/checks?check_run_id=14690913997
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14287265191
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14286393799

@HeikoKlare could you please fix?

**Comment by HeikoKlare** [comment]
Thanks for pointing out! I'll have a look into the test failures.

Seems to be an issue on MacOS only. May be just because the timeout value for the shell to become active is too small for the hardware the test is executed on. I'll provide a PR testing that.

**Comment by SyntevoAlex** [comment]
See #724

**Comment by HeikoKlare** [comment]
One observation when taking another look at the logs: the test issue seems to somehow be related to either `Test_org_eclipse_swt_widgets_Sash` or `Test_org_eclipse_swt_widgets_Tree`. The latter test class is the one that is first to fail and the former one is the last to still succeed during test runs. All tests executed afterwards fail and all tests executed before succed. The test class execution order is deterministic and the class at which the tests start to fail as well. So this does not seem to be some indeterministic OS behavior but an actual issue introduced by one of these test classes.

**Comment by HeikoKlare** [comment]
Fixed by #617.
