### ISSUE TITLE
SWT should require Java 17 runtime in 4.28

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#625]
### Discussed in https://github.com/eclipse-platform/eclipse.platform.swt/discussions/623

I've just noticed that SWT is still requires at least Java 11, even if the almost everything in platform (except equinox) is moved to Java 17.

Note that the [Eclipse project Plan for 4.28](https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_28.xml) only sees Java 17 as supported platform.

We should switch SWT to require Java 17 runtime for 4.28 M2.

I will provide a PR.

**Comment by iloveeclipse** [comment]
@HannesWell : For ppc64le build, which JVM is to use here:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/c26d1ff0248c9191a81e6cd5a94607bf77c4f740/Jenkinsfile#L146

**Comment by iloveeclipse** [comment]
Currently I'm stuck on some strange Jenkins build results in https://github.com/eclipse-platform/eclipse.platform.swt/pull/627. If anyone has ideas, please comment there.

**Comment by HannesWell** [comment]
> @HannesWell : For ppc64le build, which JVM is to use here:
> 
> https://github.com/eclipse-platform/eclipse.platform.swt/blob/c26d1ff0248c9191a81e6cd5a94607bf77c4f740/Jenkinsfile#L146

That's a JVM/JDK installed by the EFDN infra team and you want to use another one you have to open a ticket and ask them to add another one tot the build machines dedicated for ppc64le (see https://ci.eclipse.org/releng/label/swt.natives-gtk.linux.ppc64le/), which is at the moment only https://ci.eclipse.org/releng/label/swt.natives-gtk.linux.ppc64le/.

But that and the other JDKs in that part assigned to the JAVA_HOME env variable only provide the headers used for the JNI code.
Since (I assume that) the Java JNI code headers should be equivalent over the Java versions it should be sufficient the leave them untouched. The SWT natives build against the Java-11 headers work with java-17 JRE already and I assume they will do it even when the bundles require java-17.
Nevertheless on the long run those JVMs should be updated. Looking at the win32/library/build.bat it seems that for windows only the SWT_JAVA_HOME is honored, while for other Platforms JAVA_HOME is used:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/04678a28607971268382a53f4b85c0b176b02add/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/win32/library/build.bat#L53-L66

That's probably something that should be unified.

> Note, we also still have build files that require Java 11, see #626. Not sure if we can switch sources to Java 17 and still run build with 11.

The `Build` stage itself runs with a Java-17 JDK on the PATH already.
https://github.com/eclipse-platform/eclipse.platform.swt/blob/04678a28607971268382a53f4b85c0b176b02add/Jenkinsfile#L282
In the stages that perform the SWT natives build respectively check if that is necessary and handle committing etc. Java-11 is indeed required if the ant tasks use javascript. But one of the goals of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513 is to get rid of ANT as much as reasonable possible, which (hopefully) then makes the use of embedded javascript obsolete.
But in the meantime I think we can stay with the current setup, even if the bundles require Java-17 since in the build and test stage Java-17 is used as said above.


> Currently I'm stuck on some strange Jenkins build results in #627. If anyone has ideas, please comment there.

Fixed with #628 .

**Comment by iloveeclipse** [comment]
SDK build failed with https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28/63/console
```
08:53:30  [INFO] Resolving dependencies of MavenProject: org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:3.124.0-SNAPSHOT @ /home/jenkins/agent/workspace/Builds/I-build-4.28/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/pom.xml
08:53:30  [ERROR] org.eclipse.swt 3.124.0.qualifier requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=17)) but the current resolution context uses [a.jre.javase 11.0.0]
08:53:30  [INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, org.eclipse.swt.buildtime=true, osgi.arch=x86_64}
08:53:30  [ERROR] Cannot resolve project dependencies:
08:53:30  [ERROR]   Software being installed: org.eclipse.swt.win32.win32.x86_64 3.124.0.qualifier
08:53:30  [ERROR]   Missing requirement: org.eclipse.swt 3.124.0.qualifier requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found
08:53:30  [ERROR]   Cannot satisfy dependency: org.eclipse.swt.win32.win32.x86_64 3.124.0.qualifier depends on: osgi.bundle; org.eclipse.swt [3.124.0,4.0.0)
```

@laeubi : that seem to be a difference between Jenkins / official build. Where is th eproblem?

**Comment by iloveeclipse** [comment]
Is **that** the reason: https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/36 ?
